### ISSUE TITLE
HUD issue - when the lateral windows are hidden it's still impossible to click through

### ISSUE THREAD

**Issue by ludmattern** [ludmattern/ft_transcendence#11]
need to remove the pointer events on the container on that particular event

**Comment by ludmattern** [comment]
fixed on commit 8400ee214e747ec2769d6ac17be7ad8e1a2c5277

in `hud_style.css`  had to set and toggle the `pointer-events` of the parent element :

before :

```css
#hud-body .r-side-window,
#hud-body .l-side-window {
  pointer-events: all;
}
```

now :

```css
#hud-body .r-side-window,
#hud-body .l-side-window {
  pointer-events: none;
}

#hud-body .r-side-window:has( .right-side-window-expander.active),
#hud-body .l-side-window:has( .left-side-window-expander.active) {
pointer-events: all;
}
```
