### ISSUE TITLE
How to add a microservice.

### ISSUE THREAD

**Issue by maeumdaerohae** [ludmattern/ft_transcendence#17]
- Copy one of the existing service (for example, user-service folder)
- Rename it as such ("nameofservice"-service)
- settings.py: change ROOT_URLCONF and WSGI in order to match "nameofservice".urls and "nameofservice".wsgi.application for example.
- urls.py: empty urlpatterns table, will need to add correct ones later on.
- wsgi.py: change os.environ.setdefault('DJANGO_SETTINGS_MODULE', '"nameofservice".settings')
- models.py: change this to match data tables you'll need.
- views.py: empty this at first.
- Dockerfile: get rid of useless RUN pip install YYY
- manage.py : os.environ.setdefault('DJANGO_SETTINGS_MODULE', '"nameofservice".settings')
- requirements.txt: get rid of things you won't use, (usually keep Django>=4.2 && psycopg2==2.9.7 at least)

- in docker-compose.yml:

```
  nameofservice-service:
    build:
      context: ./backend/nameofservice-service
    container_name: nameofservice_service
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./secret/.env
    networks:
      - backend_network
      - frontend_network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres_db
      - DB_PORT=5432
    ports:
      - "300X:300X"
    

  nginx:
    build:
      context: ./nginx
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./frontend:/usr/share/nginx/html/frontend:ro
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
      nameofservice-service:
        condition: service_started

    networks:
      - frontend_network
      - backend_network
```
- nginx.conf:
```
      location /api/user-service/ {
             proxy_pass http://user-service:3002/;
        }
        location /api/nameofservice-service/ {
             proxy_pass http://nameofservice-service:300X/;
        }
```

Until here, this was only to get the service to be working when making the project.

Now need to fill in the files to suit your needs.
